### ISSUE TITLE
A small typo error in  Surah Ambiya- Surah 21

### ISSUE THREAD

**Issue by SyedAmeenhyd** [amrayn/planner#18]
As Salaamu Alaikum
The words Bismillah Hir rahman Nir Raheem has been printed before the first Ayaat. Not as a header as in all surah's but as a part of the ayaat.

The words are repeating. Kindly check.

**Comment by abumq** [comment]
You mean this? https://muflihun.com/21
If so this is with all the surahs. Please confirm

**Comment by SyedAmeenhyd** [comment]
Yes, I saw it later , it is with all the surah’s.

 

In spite of the heading of Bismillah Hir Rahman Nir raheem.

**Comment by abumq** [comment]
The heading is treated different than contents. Leaving it as is as this is not a typo.
