### ISSUE TITLE
the translation of hadith no 5064

### ISSUE THREAD

**Issue by syedanwaar** [amrayn/planner#19]

**Comment by syedanwaar** [comment]
Narrated Abdullah ibn Khubayb:

We went out one rainy and intensely dark night to look for the Messenger of Allah (Peace be upon him) to lead us in prayer, and when we found him, he asked: Have you prayed?, but I did not say anything. So he said: Say, but I did not say anything. He again said: Say, but I did not say anything. He then said: Say. So I said: What am I to say? He said: Say: "Say, He is Allah, One," and al-Mu'awwadhatan thirty three times in the morning and evening; they will serve you for every purpose.    Its not thirty three times it is three times

**Comment by mkhan3189** [comment]
Can you please clarify what is the issue? also link will also help. Thanks

**Comment by syedanwaar** [comment]
The issue is that the traslation of the word salasa marrat in arabic is done as thirty three whereas it means three times when i check on sunnah.com i m confused

**Comment by syedanwaar** [comment]
https://muflihun.com/abudawood/43/5064

**Comment by abumq** [comment]
Jazaak Allahu khayraa yaa akhi, we have confirmed your report by https://muflihun.com/books/sunan-abu-dawud -> Vol 5 -> page 400 and have fixed it
Baarak Allahu lak

**Comment by syedanwaar** [comment]
Masha allah brother i appreciate the quick service

**Comment by syedanwaar** [comment]
May allah bless you with good

**Comment by abumq** [comment]
and you too, wassalam wa rahamatullahi wa barakatuh
