### ISSUE TITLE
Different Hadith 

### ISSUE THREAD

**Issue by faranwkh** [amrayn/planner#20]
hi, i was searcing for a particular hadith(Sunan Abi Dawud - 3826) and found that on other credible sites it was different than what is quoted at your site. kindly look into it.
 
muflihun Reference: [https://muflihun.com/abudawood/28/3826](url)
sunnah.com reference [https://sunnah.com/abudawud/28](url)
another reference [http://www.gowister.com/hadith/abudawud/3832/](url)

**Comment by abumq** [comment]
This is not an issue, it's matter of which number you look at,

all of these sites have international numbering 3826 which is https://muflihun.com/abudawood/28/3817 

If you notice on sunnah.com for example, it has `Reference : Sunan Abi Dawud 3826` and `English translation : Book 27, Hadith 3817` which is what muflihun.com is also showing 

we have confirmed this in darussalām print (https://muflihun.com/books/sunan-abu-dawud) => vol 4, page 292
