### ISSUE TITLE
Wrong Hadees No in Sunan Abudaud Vol 22

### ISSUE THREAD

**Issue by mahju** [amrayn/planner#21]
AA
Hadees No. 3245 in your database is not the same as in the hadees book. Actually Hadees No. 3251 in the book
I have attached the pic from the book and from your database
![wrong hadees no](https://user-images.githubusercontent.com/31284454/29624781-72458edc-8843-11e7-9ad1-20e45fb036bd.PNG)
![wrong hadees-1](https://user-images.githubusercontent.com/31284454/29624782-724adaae-8843-11e7-9b52-520aa1ac1039.PNG)
Thanks

**Comment by abumq** [comment]
You're looking at difference reference. Darussalaam uses international numbering which is also mentioned in `References` section of the page

![29624782-724adaae-8843-11e7-9b52-520aa1ac1039](https://user-images.githubusercontent.com/1683515/42194624-24149a20-7eb8-11e8-86fd-38ae438173ea.png)

From the book:
<img width="641" alt="book" src="https://user-images.githubusercontent.com/1683515/42194647-4295ee4a-7eb8-11e8-9af5-699c5129c793.png">

And thanks for the mention may Allah jalla wa alaa reward you with goodness, i have updated to match the exact translation
