### ISSUE TITLE
Sahih Bokhari (11:626) translation

### ISSUE THREAD

**Issue by NerminLafi** [amrayn/planner#22]
Please reconcile the translation of this hadith, there should be a clear mention that the prophet did not order ppl to be burnt, however, please include a referance to the hadith's entro and mention prophet said I would have almost asked for them to be flamed.

**Comment by abumq** [comment]
The text of translation means same as text of arabic for this narration

لَيْسَ صَلاَةٌ أَثْقَلَ عَلَى الْمُنَافِقِينَ مِنَ الْفَجْرِ وَالْعِشَاءِ، وَلَوْ يَعْلَمُونَ مَا فِيهِمَا لأَتَوْهُمَا وَلَوْ حَبْوًا، لَقَدْ هَمَمْتُ أَنْ آمُرَ الْمُؤَذِّنَ فَيُقِيمَ، ثُمَّ آمُرَ رَجُلاً يَؤُمُّ النَّاسَ، ثُمَّ آخُذَ شُعَلاً مِنْ نَارٍ فَأُحَرِّقَ عَلَى مَنْ لاَ يَخْرُجُ إِلَى الصَّلاَةِ بَعْدُ

No prayer is harder for the hypocrites than the Fajr and the 'Isha' prayers and if they knew the reward for these prayers at their respective times, they would certainly present themselves (in the mosques) even if they had to crawl." The Prophet added, "Certainly I decided to order the Mu'adh-dhin (call-maker) to pronounce Iqama and order a man to lead the prayer and then take a fire flame to burn all those who had not left their houses so far for the prayer along with their houses.


if it's not mentioned in original narration we cannot add but i have added cross-reference link to the explanation though https://muflihun.com/bukhari/11/626
