### ISSUE TITLE
Typo in bukhari/18/154

### ISSUE THREAD

**Issue by rosesonfire** [amrayn/planner#24]
in [https://muflihun.com/bukhari/18/154](https://muflihun.com/bukhari/18/154), there seems to be a typo:

Currently it reads:

> The sun and the moon are two signs **against** the signs of Allah

Should be something like:
> The sun and the moon are two signs **amongst** the signs of Allah

Or something like:

> The sun and the moon are two signs **from among** the signs of Allah

**Comment by abumq** [comment]
Fixed. Jazaak Allahu khayraa
