### ISSUE TITLE
Wrong wording for a hadith

### ISSUE THREAD

**Issue by Khaya-Lamu** [amrayn/planner#26]
Assalamu Alaikum,

https://muflihun.com/tirmidhi/45/3500 ---> There is an error in the Arabic text. 

This is written "**وَوَسِّعْ لِي فِي رِزْقِي**" on the site whereas it should be "**وَوَسِّعْ لِي فِي دَارِي**" as there is no mention of "Rizq" in this part in the original Arabic script & the translation also indicates that the current one is wrong.

**Comment by abumq** [comment]
Walykumussalam wa rahmatullahi wa barakatuh

What did you compare with to find it's not رزْقي? Can you please provide us with reference? May be book? We have updated the translation but you can't make arabic from translation. There can be mistakes in translations. 

JazākAllahu khayran
I'll close this and if you provide with reference we can re-open it

**Comment by Khaya-Lamu** [comment]
Salam,

Please review your version with **both** of these:

![capture](https://user-images.githubusercontent.com/40657550/43994645-4b7c990e-9dc2-11e8-8767-4a84ecd74580.PNG)
_Source:_ **Translation of "Jami at-Tirmidhi", published by Darussalam**

![untitled](https://user-images.githubusercontent.com/40657550/43994670-cd615dec-9dc2-11e8-96ab-8eef1b883913.png)
_Source:_ **"Tuhfatul Ahwazi bi Sharh Jami' al-Tirmidhi" by Abdur Rahim al-Mubarakpori** (Sorry for the bad picture quality)

You can see both of them doesn't have رزْقي in the Arabic text. Also, change _"provision"_ to "**abode**". 

JazākAllahu khayran
