### ISSUE TITLE
Wrong Translation

### ISSUE THREAD

**Issue by makkila** [amrayn/planner#28]
The translation of the hadith here https://muflihun.com/bukhari/34/344 says "the bartering of gold for silver is riba", but the arabic actually talks about trading gold for gold and silver for silver.

**Comment by abumq** [comment]
@makkila I have cross-checked with darussalaam publications and the translation matches that which is obviously more reliable.

I have also added a cross-reference to the PDF version on [hadith page](https://muflihun.com/bukhari/34/344)

[Saheeh al-Bukhari, Darussalaam Publications, Vol. 3, Page 198](http://rc.muflihun.com/books/sahih-al-bukhari/vol-3.pdf)

**Comment by makkila** [comment]
Sorry maybe I'm looking in the wrong place but page 198 of the PDF also says gold for gold?

**Comment by abumq** [comment]
Jazaak Allahu khayran, i should have read the issue properly, I have fixed it :) Ma'salaam
