### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by onelightwithin** [amrayn/planner#30]
https://muflihun.com/muslim/27/5594

small typo error, please double check.

**Comment by onelightwithin** [comment]
"hell) your lord in performing ablution"

english translation portion
hell)
should be
help

**Comment by onelightwithin** [comment]
Messenaer 

should be 

Messenger

**Comment by abumq** [comment]
Fixed. Sorry for the delay, this was due to re-design and on-going improvements.
