### ISSUE TITLE
Hadees Correction

### ISSUE THREAD

**Issue by amirak17** [amrayn/planner#33]
السلام عليكم ورحمة الله وبركاته

There is a typo in the hadees ﷺ on the following link, where it says "n slippers" 
https://muflihun.com/bukhari/3/136

From another hadees on the following link
https://muflihun.com/bukhari/29/68

We may conclude that it should say "no slippers".

Kindly make the correction.

جزاك اللهُ خيرًا

**Comment by abumq** [comment]
Walaaykumussalam wa rahamatullahi wa barakaatuh,

Jazaak Allahu khayraa, it's fixed now
