### ISSUE TITLE
Missed word in Arabic 

### ISSUE THREAD

**Issue by Leeness** [amrayn/planner#34]
https://muflihun.com/bukhari/31/129
Incorrect: 
مَنِ اسْتَطَاعَ الْبَاءَةَ فَلْيَتَزَوَّجْ

Correct:
مَنِ اسْتَطَاعَ مِنْكُمُ الْبَاءَةَ فَلْيَتَزَوَّجْ

**Comment by abumq** [comment]
@Leeness 
Assalamu alaykum

After confirming from darussalam version of volume 3 of Sahih al-Bukhari, the correct is what is on website

مَنِ اسْتَطَاعَ الْبَاءَةَ فَلْيَتَزَوَّجْ

[PDF](https://www.kalamullah.com/Books/Hadith/Sahih%20al-Bukhari%20Vol.%203%20-%201773-2737.pdf) see page 85 chapter 10
