### ISSUE TITLE
Use dedicated server to the full of it's ability

### ISSUE THREAD

**Issue by abumq** [amrayn/planner#4]
When we finish migration (issue #3) we will have a lot of gates open to many new features and I will only list them in few words. We will address all the following issues below, some of them may only be idea for now and will work on them in future but will definitely need some notes about each
- Use `ffmpeg` (finally!) to convert audios on the fly whenever allowed (This allowed will be done via new column in `Audio` table)
- Clean the code as much as possible -- As part of these changes we will also remove old / unused code and restructure existing code

**Comment by mkhan3189** [comment]
SceduledJob has been done before migration and working like charm. Need notifier

**Comment by abumq** [comment]
Closing this, will create seperate issues for each of the items
