### ISSUE TITLE
Add bookmark feature for tafasir

### ISSUE THREAD

**Issue by waqaskhan540** [amrayn/planner#68]
Add feature to bookmark a point in the tafsir of a particular verse so that users could continue from where they left.

**Comment by abumq** [comment]
Jazaak Allahu khayraa for this feature request brother. This has been added in new Qur'an experience and in search results.

search page:
<img width="400" alt="Screen Shot 2023-03-17 at 23 54 34" src="https://user-images.githubusercontent.com/1683515/225910947-138526d5-52b6-4e1a-ad50-f37cebb6742e.png">
and on new Quran page:
<img width="400" alt="Screen Shot 2023-03-17 at 23 55 39" src="https://user-images.githubusercontent.com/1683515/225910960-09fee55d-91d8-49fc-a714-0aaf221636de.png">
